sudo: required
services:
  - docker

before_install:
  - docker build -t dockeryoutube -f Dockerfile.dev .

script:
  - docker run -e CI=true dockeryoutube npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"
  region: "ap-south-1"
  app: "docker-youtube"
  env: "DockerYoutube-env"
  bucket_name: "elasticbeanstalk-ap-south-1-345800986069"
  bucket_path: "docker-youtube"
  on:
    branch: master
